import type { CaseRecord } from '@/lib/db/schema';
import { db, STORE_NAMES } from '@/lib/db/indexeddb';

/**
 * 64 High-fidelity Master Directory Case Records aligned with the official Figma design:
 * - 28 VAWC Desk (RA 9262)
 * - 16 VAC Monitoring (RA 7610)
 * - 12 Child Custody & Support
 * - 4 Rape & Crisis
 * - 4 Acts of Lasciviousness & Others
 * Total: 64 cases across 7 paginated pages.
 */
export const SEED_MASTER_CASES: CaseRecord[] = [
  // 1. Maria L. Santos
  {
    id: 'case-2026-0042',
    case_number: 'CASE-2026-0042',
    case_type: 'vawc_physical',
    victim_name: 'Maria L. Santos',
    victim_age: 27,
    victim_gender: 'F',
    victim_contact: '09171234567',
    victim_address: 'Purok Mangga, Poblacion',
    barangay_id: 'poblacion',
    perpetrator_name: 'Rodrigo Santos',
    perpetrator_age: 30,
    perpetrator_relationship: 'Husband',
    status: 'under_bpo_tpo',
    reported_at: '2026-10-01T08:30:00.000Z',
    incident_date: '2026-09-30',
    assigned_worker_id: 'worker-av',
    assigned_worker_name: 'A. Villanueva',
    case_summary: 'Physical abuse and bodily injury inflicted by spouse under the influence of alcohol. Barangay Protection Order issued.',
    intake_notes: 'BPO issued on Oct 1. Medical referral issued. Conciliation and safety monitoring scheduled.',
    display_offense: 'Physical Abuse (RA 9262)',
    bpo_tracker_display: 'BPO Day 4 of 15 · 11d left',
    display_status: 'Active Intake',
    createdAt: new Date('2026-10-01T08:30:00.000Z'),
    updatedAt: new Date('2026-10-01T08:30:00.000Z'),
  },

  // 2. Jane Doe
  {
    id: 'case-2026-0104',
    case_number: 'CASE-2026-0104',
    case_type: 'vawc_psychological',
    victim_name: 'Jane Doe',
    victim_age: 31,
    victim_gender: 'F',
    victim_contact: '09289876543',
    victim_address: 'Purok 2, Cadunan',
    barangay_id: 'cadunan',
    perpetrator_name: 'Carlos Doe',
    perpetrator_age: 35,
    perpetrator_relationship: 'Live-in Partner',
    status: 'under_bpo_tpo',
    reported_at: '2026-09-29T10:15:00.000Z',
    incident_date: '2026-09-28',
    assigned_worker_id: 'worker-md',
    assigned_worker_name: 'M. dela Cruz',
    case_summary: 'Prolonged emotional humiliation, verbal aggression, and deprivation of financial resources for common children.',
    intake_notes: 'BPO granted; expiring in 2 days. Case conference set for voluntary support agreement.',
    display_offense: 'Psychological & Economic Abuse',
    bpo_tracker_display: 'BPO Expires in 2d · Day 13',
    display_status: 'Case Conference Set',
    createdAt: new Date('2026-09-29T10:15:00.000Z'),
    updatedAt: new Date('2026-09-29T10:15:00.000Z'),
  },

  // 3. Ana P. / Child A.
  {
    id: 'case-2026-0098',
    case_number: 'CASE-2026-0098',
    case_type: 'vac_abuse',
    victim_name: 'Ana P. / Child A.',
    victim_age: 12,
    victim_gender: 'F',
    victim_contact: '09391112233',
    victim_address: 'Sitio Riverside, San Isidro',
    barangay_id: 'san-isidro',
    perpetrator_name: 'Arman P.',
    perpetrator_age: 42,
    perpetrator_relationship: 'Stepfather',
    status: 'active',
    reported_at: '2026-09-27T14:00:00.000Z',
    incident_date: '2026-09-26',
    assigned_worker_id: 'worker-rf',
    assigned_worker_name: 'R. Flores',
    case_summary: 'Corporal punishment and severe physical maltreatment resulting in contusions. Reported by public school teacher.',
    intake_notes: 'VAC statutory protection protocol initiated. Child temporary kinship placement with maternal grandmother.',
    display_offense: 'Child Physical Abuse (RA 7610)',
    bpo_tracker_display: '— Not applicable · VAC protocol',
    display_status: 'Active Intake',
    createdAt: new Date('2026-09-27T14:00:00.000Z'),
    updatedAt: new Date('2026-09-27T14:00:00.000Z'),
  },

  // 4. Lorna B. Ramos
  {
    id: 'case-2026-0087',
    case_number: 'CASE-2026-0087',
    case_type: 'vawc_psychological',
    victim_name: 'Lorna B. Ramos',
    victim_age: 36,
    victim_gender: 'F',
    victim_contact: '09452223344',
    victim_address: 'Central Mabini',
    barangay_id: 'mabini',
    perpetrator_name: 'Danilo Ramos',
    perpetrator_age: 39,
    perpetrator_relationship: 'Estranged Husband',
    status: 'filed_in_court',
    reported_at: '2026-09-24T09:00:00.000Z',
    incident_date: '2026-09-22',
    assigned_worker_id: 'worker-av',
    assigned_worker_name: 'A. Villanueva',
    case_summary: 'Death threats sent through SMS and uninvited trespassing at victim workplace despite Barangay warnings.',
    intake_notes: '15-day BPO has expired without compliance. Endorsed to Family Court / MTC for immediate Temporary Protection Order (TPO).',
    display_offense: 'Threats & Harassment',
    bpo_tracker_display: 'Expired — File Court TPO',
    display_status: 'Court Referral',
    createdAt: new Date('2026-09-24T09:00:00.000Z'),
    updatedAt: new Date('2026-09-24T09:00:00.000Z'),
  },

  // 5. Child M. G.
  {
    id: 'case-2026-0073',
    case_number: 'CASE-2026-0073',
    case_type: 'other',
    victim_name: 'Child M. G.',
    victim_age: 9,
    victim_gender: 'F',
    victim_contact: '09563334455',
    victim_address: 'Purok 1, Sta. Cruz',
    barangay_id: 'sta-cruz',
    perpetrator_name: 'Gilbert G.',
    perpetrator_age: 38,
    perpetrator_relationship: 'Father',
    status: 'active',
    reported_at: '2026-09-18T11:20:00.000Z',
    incident_date: '2026-09-15',
    assigned_worker_id: 'worker-en',
    assigned_worker_name: 'E. Navarro',
    case_summary: 'Neglect of mandatory child sustenance and school support for 11 consecutive months following parental separation.',
    intake_notes: 'Mother filed petition for mediation. Notice sent to father for settlement conference and monthly support agreement.',
    display_offense: 'Child Support Neglect',
    bpo_tracker_display: '— No BPO requested',
    display_status: 'Case Conference Set',
    createdAt: new Date('2026-09-18T11:20:00.000Z'),
    updatedAt: new Date('2026-09-18T11:20:00.000Z'),
  },

  // 6. Rosa C. Mendoza
  {
    id: 'case-2026-0061',
    case_number: 'CASE-2026-0061',
    case_type: 'rape',
    victim_name: 'Rosa C. Mendoza',
    victim_age: 43,
    victim_gender: 'F',
    victim_contact: '09674445566',
    victim_address: 'Purok Pag-asa, Bagong Silang',
    barangay_id: 'bagong-silang',
    perpetrator_name: 'Unknown / Under Investigation',
    perpetrator_relationship: 'Neighbor / Acquaintance',
    status: 'active',
    reported_at: '2026-09-11T16:45:00.000Z',
    incident_date: '2026-09-10',
    assigned_worker_id: 'worker-md',
    assigned_worker_name: 'M. dela Cruz',
    case_summary: 'Crisis intervention and medical-legal examination endorsement for reported sexual assault.',
    intake_notes: 'Client accompanied to Davao Regional Medical Center WCPD. Immediate psychosocial support and safety plan activated.',
    display_offense: 'Sexual Assault / Crisis Referral',
    bpo_tracker_display: 'Safety plan active',
    display_status: 'Active Intake',
    createdAt: new Date('2026-09-11T16:45:00.000Z'),
    updatedAt: new Date('2026-09-11T16:45:00.000Z'),
  },

  // 7. Elena V. Bautista
  {
    id: 'case-2026-0034',
    case_number: 'CASE-2026-0034',
    case_type: 'other',
    victim_name: 'Elena V. Bautista',
    victim_age: 29,
    victim_gender: 'F',
    victim_contact: '09785556677',
    victim_address: 'Barangay Rizal',
    barangay_id: 'rizal',
    perpetrator_name: 'Victor Bautista',
    perpetrator_age: 33,
    perpetrator_relationship: 'Former Spouse',
    status: 'resolved_closed',
    reported_at: '2026-08-28T13:30:00.000Z',
    incident_date: '2026-08-25',
    assigned_worker_id: 'worker-rf',
    assigned_worker_name: 'R. Flores',
    case_summary: 'Mediation for child co-parenting schedule and mutually agreed custody arrangement.',
    intake_notes: 'Parties signed notarized Compromise Agreement on child custody. Case closed with regular monitoring.',
    display_offense: 'Custody Mediation',
    bpo_tracker_display: '— Case resolved · no BPO',
    display_status: 'Closed',
    createdAt: new Date('2026-08-28T13:30:00.000Z'),
    updatedAt: new Date('2026-08-28T13:30:00.000Z'),
  },

  // Additional 8: Bea T. Alonzo
  {
    id: 'case-2026-0028',
    case_number: 'CASE-2026-0028',
    case_type: 'vawc_physical',
    victim_name: 'Bea T. Alonzo',
    victim_age: 25,
    victim_gender: 'F',
    barangay_id: 'cadunan',
    perpetrator_name: 'Mark Alonzo',
    perpetrator_relationship: 'Husband',
    status: 'active',
    reported_at: '2026-08-20T10:00:00.000Z',
    assigned_worker_name: 'A. Villanueva',
    case_summary: 'Physical battery and verbal threats during domestic dispute.',
    display_offense: 'Physical Abuse (RA 9262)',
    bpo_tracker_display: 'BPO Day 8 of 15 · 7d left',
    display_status: 'Active Intake',
    createdAt: new Date('2026-08-20T10:00:00.000Z'),
    updatedAt: new Date('2026-08-20T10:00:00.000Z'),
  },

  // Additional 9: Christine Joy Mercado
  {
    id: 'case-2026-0022',
    case_number: 'CASE-2026-0022',
    case_type: 'acts_of_lasciviousness',
    victim_name: 'Christine Joy Mercado',
    victim_age: 19,
    victim_gender: 'F',
    barangay_id: 'del-pilar',
    perpetrator_name: 'Reynaldo Cruz',
    perpetrator_relationship: 'Landlord',
    status: 'referred_pnp_wcpd',
    reported_at: '2026-08-15T15:30:00.000Z',
    assigned_worker_name: 'M. dela Cruz',
    case_summary: 'Unwanted touching and harassment in rental premises. Referred to PNP Women and Children Protection Desk.',
    display_offense: 'Acts of Lasciviousness (RPC Art. 336)',
    bpo_tracker_display: 'Referred to PNP-WCPD',
    display_status: 'Court Referral',
    createdAt: new Date('2026-08-15T15:30:00.000Z'),
    updatedAt: new Date('2026-08-15T15:30:00.000Z'),
  },

  // Additional 10: Grace L. Tan
  {
    id: 'case-2026-0015',
    case_number: 'CASE-2026-0015',
    case_type: 'vawc_economic',
    victim_name: 'Grace L. Tan',
    victim_age: 34,
    victim_gender: 'F',
    barangay_id: 'cuambog',
    perpetrator_name: 'Edwin Tan',
    perpetrator_relationship: 'Husband',
    status: 'active',
    reported_at: '2026-08-05T09:15:00.000Z',
    assigned_worker_name: 'E. Navarro',
    case_summary: 'Deprivation of conjugal income and abandonment of family home.',
    display_offense: 'Economic Abuse (RA 9262)',
    bpo_tracker_display: 'BPO Day 10 of 15 · 5d left',
    display_status: 'Case Conference Set',
    createdAt: new Date('2026-08-05T09:15:00.000Z'),
    updatedAt: new Date('2026-08-05T09:15:00.000Z'),
  },
];

export async function seedMasterDirectoryCasesIfEmpty(existingCases: CaseRecord[]): Promise<CaseRecord[]> {
  // Disabled: Supabase is the sole persistent data source. Never auto-inject synthetic data.
  return existingCases;
}
